### ISSUE TITLE
Unused global variable

### ISSUE THREAD

**Issue by 3A43Mka** [Sashko26/lab1_SEM#1]
https://github.com/Sashko26/lab1_SEM/blob/016b77662b24b2427dd5d09262364658daeea19a/index.js#L5
Why is this variable here and why is it global? If it is used elsewhere, maybe declare it in respective file?

**Comment by Sashko26** [comment]
Thanks for the comment, the variable "i" was left in the code by mistake, it was not used in this module at all, so I removed it.
