### ISSUE TITLE
Errors language

### ISSUE THREAD

**Issue by 3A43Mka** [Sashko26/lab1_SEM#3]
https://github.com/Sashko26/lab1_SEM/blob/016b77662b24b2427dd5d09262364658daeea19a/euroZone.js#L126
The code throws errors with English or Ukrainian descriptions, which is a bit out of place. Maybe make it more consistent and use only one language across the entire app?

**Comment by Sashko26** [comment]
Thank you for your comment. All text messages in the project are now written in English.
