### ISSUE TITLE
magic const

### ISSUE THREAD

**Issue by IanaKhitsko** [Sashko26/lab1_SEM#5]
https://github.com/Sashko26/lab1_SEM/blob/016b77662b24b2427dd5d09262364658daeea19a/city.js#L22

the same here - please introduce const

**Comment by IanaKhitsko** [comment]
https://github.com/Sashko26/lab1_SEM/blob/016b77662b24b2427dd5d09262364658daeea19a/city.js#L35

and here please and further in this file please

**Comment by Sashko26** [comment]
Thanks for the comment, I added another constant.
