### ISSUE TITLE
Random return 

### ISSUE THREAD

**Issue by IanaKhitsko** [Sashko26/lab1_SEM#7]
https://github.com/Sashko26/lab1_SEM/blob/016b77662b24b2427dd5d09262364658daeea19a/city.js#L103

what if rand >0 ,what value shall be returned?

**Comment by IanaKhitsko** [comment]
Is this code used anywhere?

**Comment by Sashko26** [comment]
Thank you for your comments. The function that was considered in the code had to be removed because it was not used in the project at all. Since the function has been removed, the fix is no longer relevant.
