### ISSUE TITLE
isCompleteness 

### ISSUE THREAD

**Issue by IanaKhitsko** [Sashko26/lab1_SEM#8]
https://github.com/Sashko26/lab1_SEM/blob/016b77662b24b2427dd5d09262364658daeea19a/country.js#L37

What if this.isCompleteness == true here. Do we need to check all cities again?

**Comment by Sashko26** [comment]
Thank you for your comment. The checkCompleteness function has been improved and now it does not iterate if this.isCompleteness == true.
